### ISSUE TITLE
error message incorrectly blames lang/prim.rkt for error in my code

### ISSUE THREAD

**Issue by spdegabrielle** [racket/htdp#103]
My sample code below supplies a procedure where it should supply an image and triggers an error that blames `prim.rkt` incorrectly. 

I am using `version 7.7.0.9--2020-06-14(-/f) [3m].` so I don't think this is the same as #101 

`.../lang/prim.rkt:24:44: image-height: expects an image as first argument, given #<procedure:rectw>`

```racket
#lang racket/base
(require 2htdp/image)
(define rect (rectangle 4 2 'solid 'silver))
(define (rectw w) (rectangle w 2 'solid 'silver))
(define lander-heighta (image-height rect))
(define lander-heightb (image-height (rectw 10)))
(define lander-heightc (image-height rectw))
```

![image](https://user-images.githubusercontent.com/108047/84786861-35034600-afe5-11ea-9915-330966554610.png)

**Comment by mfelleisen** [comment]
I confirm for BC. 

In CS (admittedly slightly older) the error message is different and points to the place where the function is defined:

**Comment by mfelleisen** [comment]
![Screen Shot 2020-06-16 at 10 50 29 AM](https://user-images.githubusercontent.com/1571323/84790942-f27b4280-afbf-11ea-875f-209773d1e647.png)

**Comment by spdegabrielle** [comment]
FWIW problem doesn't occur in beginning student or advanced student 
![image](https://user-images.githubusercontent.com/108047/84801709-6b49c100-aff7-11ea-8b78-a8a4168fe6be.png)

**Comment by mflatt** [comment]
I'm seeing the same thing for BC and CS. Specifically: I see the error in both that Stephen shows, but if I touch "img-err.rkt" (so that its ".zo" is treated as out-of-date), then I see the error in both that Matthias shows. So, maybe "img-err.rkt" had an update-to-date ".zo" in Matthias's BC installation and an out-of-date ".zo" in his CS installation.
