### ISSUE TITLE
Stepper button doesn't work 

### ISSUE THREAD

**Issue by vonkoff** [racket/htdp#106]
Using v7.8 of Racket, downloaded through rack-lang.org, on Windows 10.

When I try to use the stepper button get this message back:
"send: no such method
method name: stepper-button-callback
class name: test-tab%-mixin175"

Tried on multiple projects, even happens on a simple hello world program. 
![Capture](https://user-images.githubusercontent.com/16548992/91352961-95b6b800-e7b8-11ea-84b6-f7a1fc1d4a08.PNG)

**Comment by rfindler** [comment]
I think this might have used to work....? I recall some work was involved in making the button appear in #lang htdp/bsl. Maybe there is a missing require that bring a define-member-name into scope somewhere? (Just a shot in the dark.)

**Comment by jbclements** [comment]
Well… there were other larger problems with running the stepper in the #lang languages, if I recall correctly. Basically, what’s in my head is this: "when Robby gets #lang htdp/bsl working, it’s time for me to panic and fix the stepper for it”.

John

**Comment by jbclements** [comment]
Yay! Thanks to @mikesperber , this now works. Many thanks!
