### ISSUE TITLE
string=? should not accept multiple arguments in BSL

### ISSUE THREAD

**Issue by samth** [racket/htdp#107]
The `string=?` function in BSL accepts arbitrarily many arguments, comparing the all for equality. Unfortunately, this allows students to write very incorrect programs without errors, by attempting to compare too many strings at once. Instead, `string=?` in BSL should allow only two arguments.

**Comment by mfelleisen** [comment]
Do you think this also applies to string< and friends? 

Also I am a bit reluctant with this change because it is not backwards compatible and an instructor may have demonstrated the power of prefix with this function.

**Comment by samth** [comment]
I'm much less concerned about the other string functions, because they aren't involved in the template for important data definitions. Consider this wrong function:
```
;; A TrafficLight is one of 
;;  - "red"
;; - "green"
;; - "yellow"

;; next-tl : TrafficLight -> TrafficLight
(define (next-tl tl)
   (cond [(string=? tl "red" "yellow") "green"]
             [(string=? tl "yellow" "green") "red"]
             [(string=? tl "green" "red") "yellow"])
(next-tl "red")
```

This produces the error `cond: all question results were false`. That's true, but it's far from the most helpful error we can give.

**Comment by mfelleisen** [comment]
I imagined a slightly more subtle buggy version of just that: 

```
(cond [(string=? tl "red" "yellow")] ...)
```

but yes, I have no lack of imagination understanding the problem. 

I'll fix only string=? for now. If anybody complains during the next cycle, I'll revert however.  We have had too many issues with teaching materials.

**Comment by mfelleisen** [comment]
OK, I restricted all of them. After inspecting the files, I realized that I had prepared this restriction already. 
(If we get complaints, I'll revert.)
