### ISSUE TITLE
Stepper pretty-prints booleans incorrectly

### ISSUE THREAD

**Issue by samth** [racket/htdp#11]
`#true` and `#false` should print that way -- currently they seem to print as either `#t`/`#f` or as `true`/`false` -- or sometimes both.

![screenshot from 2015-10-08 18 46 39](https://cloud.githubusercontent.com/assets/244723/10381954/fb2cadfc-6dec-11e5-8cc7-b373032ed6bf.png)

**Comment by jbclements** [comment]
fixed with 6.3 release.
