### ISSUE TITLE
Test failure after test-engine changes

### ISSUE THREAD

**Issue by samth** [racket/htdp#120]
The current stepper tests are failing. See http://drdr.racket-lang.org/55820/racket/share/pkgs/htdp-test/tests/stepper/automatic-tests.rkt

It looks like this failure started with the test-engine rewrite by @mikesperber; see http://drdr.racket-lang.org/55734/racket/share/pkgs/htdp-test/tests/stepper/automatic-tests.rkt for an older failure which has this error among others.

cc @jbclements

**Comment by mfelleisen** [comment]
Mike did inform John of the rewrite and failing tests.

**Comment by jbclements** [comment]
Yep, he did. It’s on my list.

**Comment by mikesperber** [comment]
This was fixed in 86fe96cf58e306167c523114b0b092644f63571e.
