### ISSUE TITLE
check-with poor message when initial model is bad

### ISSUE THREAD

**Issue by maueroats** [racket/htdp#123]
Racket 7.9 [bc] (also observed with 7.8)
Language level: Intermediate Student with Lambda

```racket
(require 2htdp/image)
(require 2htdp/universe)

(define (trivial x)
  (overlay x (empty-scene 300 200)))

(big-bang (circle 10 "solid" "blue")
  (check-with number?)
  (on-draw trivial))
```

Expected result: something like `error: big-bang was invoked with (circle 10 "solid" "blue") which fails to pass the check-with number? test`

Actual result:
```
ok-fmt: undefined;
 cannot use field before initialization
```

Obviously not what you want for beginners. The error used to be better (as described above).

**Comment by mfelleisen** [comment]
Thanks. Fixed.
