### ISSUE TITLE
[Feature] Enable global installation of teachpacks

### ISSUE THREAD

**Issue by Parakleta** [racket/htdp#124]
I have a multi-user machine that I would like to install the bootstrap teachpack on, but I don't want to have to modify every account to do it.  Is it possible to have some global location added where additional teachpacks can be found?

**Comment by mfelleisen** [comment]
I am not sure I understand the issue. On a multi-user machine, you can install one globally visible Racket and then install the bootstrap package thru this Racket. Every student who uses the corresponding DrRacket can then simply `(require bootstrap)` (the path depends on how you install it) and it's there. That's what we use to do for a decade before we decided all students have their own laptop anyway in the US.

**Comment by Parakleta** [comment]
I cannot find any bootstrap package.  The only thing I can find is their source distribution which contains their teachpacks.  I can find no instructions anywhere for how to install them.

**Comment by mfelleisen** [comment]
1. The question of whether the bootstrap people still have a teachpact that specializes `2htdp/universe` for their purposes, I can't answer. I suggest you contact Emmanuel Schanzer, who implemented this teachpact a long time back. 

2. If it is maintained and on the package server, there's a straightforward way to install it.  Go to the File | Install package menu in DrRacket and put in the name. It'll be installed properly. 

3. If it is only on GitHub, you can use a URL to install it, with DrRacket or `raco pkg install`.

**Comment by Parakleta** [comment]
There doesn't appear to be a package, just the file https://www.bootstrapworld.org/materials/spring2020/courses/algebra/en-us/resources/source-files.zip

Really I'm just asking for a method similar to the "Add Teachpack to List..." button that can be used to add global teachpacks.

**Comment by Parakleta** [comment]
I finally blundered my way through the documentation at https://docs.racket-lang.org/drracket/extending-drracket.html to create an `info.rkt` file which would install the teachpacks using `raco`.  Is it possibly maybe to add an example to that documentation to make it a little clearer what to do?

**Comment by mfelleisen** [comment]
I wrote to Emmanuel and suggested to turn into a plain Racket package.

**Comment by Parakleta** [comment]
Thanks.

**Comment by mfelleisen** [comment]
I got a hold of Emmanuel. The code is on GitHub _but_ it is _not_ organized as a package. 
https://github.com/bootstrapworld/BSA-drracket-teachpacks 

If you're in a hurry, I'd say copy the code and make it a package that you install locally for the OS-wide Racket installation.

**Comment by Parakleta** [comment]
That is essentially the contents of the file that I linked to in https://github.com/racket/htdp/issues/124#issuecomment-737585082, but it's certainly much better to be able to find it on github than buried in the course notes on bootstrapworld.org.  I modified the `info.rkt` file to add a `(define 2htdp-teachpacks ...` listing all the files in the Teachpacks directory, it just feels clumsy to have them appear as a htdp teachpack instead of a user teachpack, given that htdp is one textbook and bootstrap (or other teachpacks) will be based on their own curriculum.

**Comment by mfelleisen** [comment]
@Parakleta  

I turned Emmanuel's GitHub repo into a basic package. See  https://github.com/bootstrapworld/BSA-drracket-teachpacks/tree/master  (notice: master not main). Follow the installation instructions in the README.md to experiment. 

If he approves, I will upload it to the package server.
