### ISSUE TITLE
Images don't properly show up

### ISSUE THREAD

**Issue by carmenx** [racket/htdp#135]
In VERSION 8.0 (FEBRUARY 2021), the images don't show up properly. It works in an older version.

The error message is:
`Actual value #<image> differs from #<image>, the expected value.
in pset-05-starter (2).rkt, line 159, column 0` rather than the actual image
![image](https://user-images.githubusercontent.com/61920742/108153477-154e8100-7090-11eb-9ed7-e9ea7d8dd584.png)

Hopefully, this can be fixed quickly because my class is using this (UBC CPSC110).

Thank you for your hard work and stay safe!

**Comment by samth** [comment]
Sorry that this is affecting your class, @carmenx. Unfortunately there is not a work-around for 8.0 currently. I would recommend that your students install version 7.9, since that is not affected by this bug.

**Comment by mikesperber** [comment]
My fault, @carmenx - thanks for the report! We'll fix it for the next release, but until then @samth's advice is best.

**Comment by shhyou** [comment]
@mikesperber: I got the following error with the HEAD version of HtDP:
```
image-markup: expects only 2 arguments, but found 4
```
The source code is
```
(require 2htdp/image)
(check-expect
 (circle 50 "outline" "red")
 (circle 50 "solid" "red"))
```

**Comment by samth** [comment]
@shhyou can you open a new issue about this?
