### ISSUE TITLE
Warn of known confusing characters (e.g. curly quotes) - enhancement suggestion

### ISSUE THREAD

**Issue by maueroats** [racket/htdp#144]
Sometimes students copy and paste code from Google Docs and end up with curly quotes instead of straight quotes. 

These issues have come up recently (low incidence):

* Curly quote instead of `'` causing `'()` to be misread.
* Zero-width space
* Dash vs "en-dash"

I don't know where this suggestion should go. Would this be a modification to the reader? Foolish to even consider?

**Comment by mfelleisen** [comment]
The students' action suggests that they either (1) don't understand the necessity of programming in an IDE or (2) they share code via Google Docs. For (1), I think it's time to address this explicitly. We don't use screwdrivers to hammer nails into the wall, and we don't use document editors for creating code. For (2), they should use exchange Racket files instead (if exchanging code is even legal). 

Not worth considering.

**Comment by maueroats** [comment]
FWIW, they are observed to use DrRacket on lab computers, so I my theory is that they don't have a convenient network save mechanism (and some can't even find their file in the Documents folder vs Desktop), so they copy and paste the code they are writing into a doc. I suppose I should teach them how to copy and paste into a file on GitHub for better results with the same basic mechanics.
