### ISSUE TITLE
incorrect source line hyperlink from test-engine/racket-tests when two lines are mentioned

### ISSUE THREAD

**Issue by maueroats** [racket/htdp#152]
**What version of Racket are you using?**
8.1 [cs]

**What program did you run?**
[Note: much more minimal example added in comment.]
```
#lang racket
(require syntax/parse syntax/parse/define)
(require test-engine/racket-tests)

(module stx racket/base
  (require syntax/parse)
  (provide cond-QA)
  (define-syntax-class cond-QA
    (pattern [#:else answer]
             #:attr question #'#true)))

(require (for-syntax (submod "." stx)))

#;(begin-for-syntax
  (define-syntax-class cond-QA
    (pattern [#:else answer]
             #:attr question #'#true)))

(define-syntax-parse-rule (check-question e:cond-QA)
  e.question)

"notice that both lines are linked to the same place"

(check-expect (check-question [#:else 50])
              #true)
(test)
```

** What happened? **

The error message has both line 24 and line 10 hyperlinked to the source of the error on line 10. 

**What should have happened?**
Clicking on the underlined "line 24" part of the error message should have jumped to line 24, or possibly it should not be hyperlinked.

**If you got an error message, please include it here.**
![2021-06-19-at-23-22](https://user-images.githubusercontent.com/11153074/122662021-6f9e4200-d155-11eb-90f5-eee519511da0.png)

**Please include any other relevant details**
Linux. Running in DrRacket. Note that the problem is _not_ that the error occurs, just that the link is wrong. ~~Sorry I don't think this is "minimal" but I had a hard time modifying it to keep the error in this form.~~

**Comment by shhyou** [comment]
I've transferred this issue to racket/htdp as the Test Engine is part of HtDP.

**Comment by mfelleisen** [comment]
@rmculpepper The program causes a strange error in the macro stepper. It seems internal.
