### ISSUE TITLE
Clicking "Check Syntax" on 8.2 with "Beginning Student" shows a console window with a message

### ISSUE THREAD

**Issue by orenatol** [racket/htdp#155]
**What version of Racket are you using?**
8.2 [cs] (racket-8.2-x86_64-win32-cs.exe)

**What program did you run?**
Please include a short example that triggers the bug

After a clean install, change the language to "Beginning Student" and click "Check Syntax".
(blank tab - no code)
A new console window pops up, containing:
"namespace-attach-module: a different declaration is already in the destination namespace
  module name: #<resolved-module-path:"C:\Tools\Racket\collects\racket\class.rkt">
Its "Close" button is disabled.

**What should have happened?**
Nothing, at least that what happens on 8.1 (with a blank tab)

**If you got an error message, please include it here.**
namespace-attach-module: a different declaration is already in the destination namespace
  module name: #<resolved-module-path:"C:\Tools\Racket\collects\racket\class.rkt">

**Please include any other relevant details**
e.g., the operating system used or how you are running the code.
Windows 10 Enterprise (21H1) 64bit
![Capture](https://user-images.githubusercontent.com/59396584/126548788-70753845-93f0-46d1-bace-1ba2204c0631.PNG)

**Comment by shhyou** [comment]
Thanks for the report! I can reproduce the issue. When I tried it, although the error message showed up, Check Syntax still finished successfully. The binding arrows and documentation links were added to editor. Could you check if this is the case for you?

The error message did not show up when I'm still using htdp 6d8926510bd48aa. It appeared after I updated htdp to 2af893a0e14e2e.

**Comment by mikesperber** [comment]
Logging what I have:

The message is printed by either of the `namespace-attach-module` calls here:

https://github.com/racket/htdp/blob/fc6c2c264179b14fa6cb9ecb1ccdfd69df03a757/htdp-lib/lang/htdp-langs.rkt#L163

These have always been there, however.

**Comment by orenatol** [comment]
> 
> 
> Thanks for the report! I can reproduce the issue. When I tried it, although the error message showed up, Check Syntax still finished successfully. The binding arrows and documentation links were added to editor. Could you check if this is the case for you?
> 

Confirming!

> ...

**Comment by shhyou** [comment]
@orenatol: Thanks!

> Logging what I have:
> 
> The message is printed by either of the `namespace-attach-module` calls here:
> 
> https://github.com/racket/htdp/blob/fc6c2c264179b14fa6cb9ecb1ccdfd69df03a757/htdp-lib/lang/htdp-langs.rkt#L163
> 
> These have always been there, however.

If I comment out line 139, the error message goes away (but of course that breaks printing).

https://github.com/racket/htdp/blob/fc6c2c264179b14fa6cb9ecb1ccdfd69df03a757/htdp-lib/lang/htdp-langs.rkt#L137-L139

**Comment by mikesperber** [comment]
Thanks, @rfindler!
