### ISSUE TITLE
Comparison functions working on one argument seems counter-intuitive

### ISSUE THREAD

**Issue by dbp** [racket/htdp#185]
In BSL and above, numeric comparison functions (`>`, `<`, etc) inherit from racket/base the behavior that on a single argument, they always return true (as the arguments are in increasing/decreasing order). 

This seems like pretty bad behavior for students, as it easily hides bugs: the student forgot the second argument to the comparison, and instead of getting an error, it silently returns `#true` every time.

(This actually came up in class -- when showing quicksort, I forgot the number when filtering elements using the pivot, so ended up with code like `(filter (lambda (n) (< PIVOT)) lon)` -- which ran fine, but returned the whole list).

**Comment by mfelleisen** [comment]
As much as I agree, I am not sure we can break backwards compatibility here. @rfindler what do you think? Do it for BSL only ? We impose restrictions on `+` too, and I can't recall the rationale for not imposing it on `<` and friends.

**Comment by rfindler** [comment]
I have wondered why we didn't impose this restriction for a few years now.
Breaking old assignments and old lecture notes does seem worrying.

What about doing it only in #lang htdp/bsl
Or perhaps all of those? Does that help?

Robby

**Comment by mfelleisen** [comment]
BSL only sounds right to me.  I doubt any instructional material relies on that. — That won’t solve Daniel’s problem (with `filter`) but it’s a start.

**Comment by rfindler** [comment]
It seems like it would be nice to let people know this change was coming so
they could comment or at least have time to prepare. (As opposed to having
a student inform them that their lecture notes don't run or some equally
pressured situation.)

I don't have any good ideas on how to reach people however. Twitter?

Robby

**Comment by mfelleisen** [comment]
What’s Twitter? :-) 

After some more thinking, I have come to the conclusion I should just go ahead and restrict `<` and friends. Nobody will rely on 1-arg variants. The question is whether I should also restrict the multi-arg (> 2) variants.
