### ISSUE TITLE
missing functions in graphics/value-turtles

### ISSUE THREAD

**Issue by n-ai-up8-edu** [racket/htdp#188]
Hello,
I tested the graphics/value-turtles package. It's interesting and fun. Turtles are thought differently in this package.
The functions erase, move-offset, draw-offset and erase-offset are described in the documentation but are missing. Looking in hdtp sources, they are not defined. Difficult to use them in these conditions.
Is it planned to add them ? Is it planned to revise the doc ?

**Comment by rfindler** [comment]
Thanks for the kind words about this library!

It looks, at this point, it is probably simpler to just remove them from the documentation. If you think it would be worth adding these functions, please do reopen the issue and let's discuss.
