### ISSUE TITLE
`color-list->bitmap` has different result on my system

### ISSUE THREAD

**Issue by jasonhemann** [racket/htdp#191]
The documentation for that function says exactly how to build the bitmap

![image](https://user-images.githubusercontent.com/1329370/219893047-fa71f285-5329-453c-9f5b-992ad327365b.png)

And that's precisely [how the scribble does it](https://github.com/racket/htdp/blob/19bb047867dd2a11c40f4e880929141b72ffbcea/htdp-doc/teachpack/2htdp/scribblings/image.scrbl#L1639-L1643).

But on my M1 MacOS Monterey system running 8.7, what I see is the following:

![image](https://user-images.githubusercontent.com/1329370/219893748-e88b6d54-686d-4819-af92-a699a8498f92.png)

What explains this difference? Is this expected?

**Comment by sorawee** [comment]
See also #148

**Comment by jasonhemann** [comment]
Ah. Dupe. Thank you.
