### ISSUE TITLE
Inconsistency w/signatures in, at least, BSL

### ISSUE THREAD

**Issue by jasonhemann** [racket/htdp#192]
The scribble ultimately generated from [beginner-funs.rkt](https://github.com/racket/htdp/blob/master/htdp-lib/lang/private/beginner-funs.rkt) contains a potentially confusing mix of conventions of basic type descriptions.

[length](https://github.com/racket/htdp/blob/19bb047867dd2a11c40f4e880929141b72ffbcea/htdp-lib/lang/private/beginner-funs.rkt#L530) says it returns a `natural-number?`
[random](https://github.com/racket/htdp/blob/19bb047867dd2a11c40f4e880929141b72ffbcea/htdp-lib/lang/private/beginner-funs.rkt#L403) says it returns a `natural`
[list-ref](https://github.com/racket/htdp/blob/19bb047867dd2a11c40f4e880929141b72ffbcea/htdp-lib/lang/private/beginner-funs.rkt#L505) consumes a `natural?`
[list?](https://github.com/racket/htdp/blob/19bb047867dd2a11c40f4e880929141b72ffbcea/htdp-lib/lang/private/beginner-funs.rkt#L653) consumes `any`
[string-length](https://github.com/racket/htdp/blob/19bb047867dd2a11c40f4e880929141b72ffbcea/htdp-lib/lang/private/beginner-funs.rkt#L764) returns `nat`
[make-list](https://github.com/racket/htdp/blob/19bb047867dd2a11c40f4e880929141b72ffbcea/htdp-lib/lang/private/beginner-funs.rkt#L513) consumes `natural-number` and `any/c` 

Shouldn't there be a fixed convention, be it contract-style `/c`, predicatized `?`, or some non-predicate name for an underlying base type?

**Comment by mfelleisen** [comment]
Closed with 5ddbcc821f6dc8bcfaaebd22b208e0269caaa64f

**Comment by jasonhemann** [comment]
BTW: These were _representative_ _examples_, not an exhaustive list.

**Comment by mfelleisen** [comment]
Sure, I’ll fix others by need, my favorite working mode and unfavorite PL :-)
