### ISSUE TITLE
Test-engine docs on `display-test-results-parameter` is wrong

### ISSUE THREAD

**Issue by dbp** [racket/htdp#195]
In the docs, the parameter says that it is a function that takes test objects:

https://docs.racket-lang.org/test-engine/index.html#%28def._%28%28lib._test-engine%2Ftest-markup..rkt%29._display-test-results-parameter%29%29

But in actuality, it takes the already rendered markup:

https://github.com/racket/htdp/blob/41c2416933836e92ecaa862c9bbda7a274db62ae/htdp-lib/test-engine/test-markup.rkt#L51-L54

(the docs on `display-test-results!` are similarly wrong)

**Comment by mikesperber** [comment]
Thanks!
