### ISSUE TITLE
check-expect on Large Values

### ISSUE THREAD

**Issue by schackbrian2012** [racket/htdp#198]
Code:
In the "Intermediate Student with Lambda" language, run the following program:
`(check-expect (range 0 9999 1) 0)`

Expected Result:
An error message.

Actual Result:
DrRacket freezes, and the stop button doesn't work.

**Comment by sorawee** [comment]
Note that when I ran the above program on Racket 8.10, DrRacket only briefly (about a second) freezes. I don't know if this is because of hardware difference (I use Apple M1, which is fast), or because of the recent changes in `test-engine`.

**Comment by schackbrian2012** [comment]
@sorawee Thank you for your interest in this issue. I opened it six years ago when I was teaching a class using the "Intermediate Student with Lambda" language. I am no longer teaching that class, so I don't have Racket installed anymore, so I can't retest this issue.

**Comment by mikesperber** [comment]
I'll take a look in the next couple of days.

**Comment by mikesperber** [comment]
I just checked, and it runs fine both with #lang and the menu-based languages. As the display implementation has been replaced since this issue was filed, I guess that fixed whatever bug was there. Any objection to closing this issue?

**Comment by schackbrian2012** [comment]
@mikesperber No objection.
