### ISSUE TITLE
Runtime error causes tests above to run twice and tests below to run never

### ISSUE THREAD

**Issue by ccshan** [racket/htdp#203]
In the Beginning Student Language, running a program such as
```
(check-expect 1 1)
(check-expect 2 2)
(+ "hello" "world")
(check-expect 3 3)
(check-expect 4 4)
(check-expect 5 5)
```
produces the result
```
Both tests passed!+: expects a number, given "hello"
Both tests passed!
```
Similarly if `(+ "hello" "world")` is replaced by `(cond [false "hello"])`

This is confusing because
- The expression causing the runtime error is not highlighted in pink as usual (but rather, the cursor is moved to that expression, making it highlighted in gray due to parentheses)
- The runtime error message is not printed on its own line
- "Both tests passed!" is printed twice
- The tests below the runtime error are not run

**Comment by mfelleisen** [comment]
1. Use `#lang htdp/bsl` instead of the menu-based teaching languages. -- In that setting I can't reproduce the bug. 

2. This bug seems to be new, but I don't have time today to check it out. @mikesperber ?

**Comment by mikesperber** [comment]
@ccshan As you'll notice, there's still no newline before the error message. It is surprisingly difficult to put one there without introducing spurious, conspicuous newlines in regular output. Can you live with that? (As @mfelleisen notes, the `#lang` versions don't have this problem.)

**Comment by ccshan** [comment]
I can live with that.
