### ISSUE TITLE
incorrect error, got "this variable is not defined" but expected "divison by zero"

### ISSUE THREAD

**Issue by rfindler** [racket/htdp#205]
It looks like 61660bdc9a0920d7d62dbd7aaede4ddb381ad27d introduced a bug whereby this program:

```
(define y 0)
(define (f x) (/ x y))
(f 2)
```

in all five of the language-dialog based teaching languages produces the wrong error.

Here's the [drdr report](http://drdr.racket-lang.org/64745/racket/share/pkgs/drracket-test/tests/drracket/language-test.rkt). You can run the currently failing test with `racket -l tests/drracket/language-test`.

[ edit: corrected the commit, f497f10dd848b6f4fc97e20713af2d8608f352b3 is the wrong one; that one was fine in drdr. The commit 61660bdc9a0920d7d62dbd7aaede4ddb381ad27d is the one where the trouble started. And deinprogramm is very unlikely to be related. ]

**Comment by samth** [comment]
https://github.com/racket/htdp/commit/f497f10dd848b6f4fc97e20713af2d8608f352b3 is a test case that you added; is that the commit you meant?

**Comment by rfindler** [comment]
Whoops, thanks @samth . I've corrected the message.

@mikesperber do you mind having a look?

**Comment by rfindler** [comment]
@mikesperber also, if you have a test case for the change in 61660bdc9a0920d7d62dbd7aaede4ddb381ad27d I can try to add it to the test suite.

**Comment by mikesperber** [comment]
You can reproduce the problem by typing `y` in the REPL after running this program.

**Comment by rfindler** [comment]
Thanks, @mikesperber ! I've made a new attempt at this change in #207 . Your opinion on it would be welcome.

**Comment by jbclements** [comment]
I have a bad habit of getting things like this wrong, but the discussion in #207 suggests that this bug is now resolved. Feel free to re-open it if I'm wrong!
