### ISSUE TITLE
Fractional pen width should be allowed

### ISSUE THREAD

**Issue by ccshan** [racket/htdp#210]
According to the documentation, the following code should succeed because the `width` of a `pen` just needs to be `(and/c real? (<=/c 0 255))`:
```scheme
(require 2htdp/image)
(circle 50 "outline" (pen "red" 1.5 "solid" "round" "round"))
```
But I get `pen: expects an integer between 0 and 255 as second argument, given 1.5`

**Comment by rfindler** [comment]
Thanks!
