### ISSUE TITLE
`random` needs a better error message/documentation

### ISSUE THREAD

**Issue by camoy** [racket/htdp#217]
Here is the error, which is not ideal:

![2024-01-22_16-49](https://github.com/racket/htdp/assets/556446/38ef69d3-1d35-478d-8be4-e1f3bc4fadfd)

Furthermore, the documentation claims that `random` takes a natural number, but it does not take `0`.

cc @dbp

**Comment by mfelleisen** [comment]
Closed with 065b2a3
