### ISSUE TITLE
ASL `let` accepts the named-`let` form

### ISSUE THREAD

**Issue by shhyou** [racket/htdp#218]
This program runs in ASL:

```racket
#lang htdp/asl
(let loop ([i 0])
  (if (< i 5)
      (+ i (loop (add1 i)))
      0))
```

However, the named-`let` form is not documented. Either the documentation missed it, or this should be a syntax error.

**Comment by mfelleisen** [comment]
It is document as `(let name ...)` next to `recur` under the heading "Syntax for Advanced".

**Comment by shhyou** [comment]
Ah, indeed! I totally missed it. Thanks for pointing it out.
