### ISSUE TITLE
Hashes are printed incorrectly in ASL

### ISSUE THREAD

**Issue by shhyou** [racket/htdp#220]
In ASL, hashes are constructed using a list of 2-element lists. However, they are printed as a list of pairs in constructor-printing style:  
<https://docs.racket-lang.org/htdp-langs/advanced.html#%28def._htdp-advanced._%28%28lib._lang%2Fhtdp-advanced..rkt%29._make-hash%29%29>
> ```racket
> > (make-hash '((b 69) (e 61) (i 999)))
> (make-hash (list (cons 'i 999) (cons 'b 69) (cons 'e 61)))
> ```

The printed result should have been `(make-hash (list (list 'i 999) (list 'b 69) (list 'e 61)))`.

**Comment by mfelleisen** [comment]
I don't have time right now to dig into it, but my best guess is that this is a constructor-printer problem.  @rfindler ?

**Comment by rfindler** [comment]
It looks like a mismatch that pconvert has to be adjusted to deal with. [This line](https://github.com/racket/pconvert/blob/master/pconvert-lib/mzlib/pconvert.rkt#L375) is correct for `#lang racket` hashes, I believe, but not ASL ones. Maybe another parameter is needed?

**Comment by rfindler** [comment]
@jbclements I know that the stepper doesn't work in ASL and hashes aren't in BSL or ISL but I changed the stepper anyway, just in case it is confusing later.
