### ISSUE TITLE
No matching clause for `(make-skipped-step ...)`

### ISSUE THREAD

**Issue by bennn** [racket/htdp#23]
In BSL on Racket v6.5 and v6.6, I try to run:

```
(check-expect 0 (sqrt 2))
;; Note: (check-expect (sqrt 2) 0) is alright
```

And get this error:
```
exception raised by error display handler: match: no matching clause for (make-skipped-step ...); original exception raised: check-expect cannot compare inexact numbers. Try (check-within test 1.4142135623730951 range).
```

**Comment by rfindler** [comment]
Are you seeing this in the stepper or just by clicking "Run"? 

I'm not able to make this happen (either with Run or the stepper). Is there something else that could be required to make it go wrong?

**Comment by bennn** [comment]
Sorry, I gave a very bad description:
1. run the stepper
2. output goes to stdout; on Windows it opens a new terminal, on Mac I don't see anything unless I started DrRacket from the terminal

**Comment by rfindler** [comment]
Ah, thanks. @jbclements ?

**Comment by jbclements** [comment]
Yes, I can reproduce this. Let's see if I can figure out what's going on in the next 30 minutes.

**Comment by jbclements** [comment]
Thx for the report!
