### ISSUE TITLE
Contracts in BSL and ISL Documentation.

### ISSUE THREAD

**Issue by gfbee** [racket/htdp#34]
I have a student who extracted all the contracts from the BSL and ISL documentation (using  https://gist.github.com/adhameer/542cc3728081d2f95085ad61f3920fa8 ). The contracts, listed below, seem to be a mixture of various styles and conventions, so taking a cue from the HtDP2e Teachpacks documentation she's updating them to the current contract system.

Let me know if you think something else should be done with them, and anything non-obvious to consider while updating them. We'll submit a pull request when done.

    (X -> Y)

    (X -> Z)

    (X -> any)

    (X -> real)

    (X-1 ... X-N -> Y)

    (Y -> Z)

    (any ... -> any)

    (list X-i+1 ... X-N)

    (listof X)

    (listof any)

    (listof char)

    (nat -> X)

    (or/c #f list)

    (union #f (listof X))

    (union #f cons?)

    (union (listof any) #f)

    (union 1 1.0 0 0.0 -1 -1.0)

    (union number #f)

    X

    X-1

    Y

    any

    any/c

    boolean?

    char

    complex

    eof-object?

    exact-integer?

    image

    integer

    list

    list?

    nat

    natural-number

    natural-number?

    natural?

    number

    posn

    range

    rational?

    real

    signature

    string

    string?

    symbol

    void?

**Comment by spdegabrielle** [comment]
@gfbee was this completed?

**Comment by gfbee** [comment]
It was rejected.
