### ISSUE TITLE
Error message for pre-defined values should mention built-ins

### ISSUE THREAD

**Issue by samth** [racket/htdp#38]
The BSL program: `(define car 5)` produces the error message `car: this name was defined previously and cannot be re-defined`. Of course, the previous definition is part of the language, not in the student program. If the error message mentioned that things could be built-in to the language, that would be helpful.

I suggest: "this name is already defined in this file or is part of the language and cannot be re-defined". I'm happy to make the change if that sounds good to people.

**Comment by mfelleisen** [comment]
> On Aug 28, 2017, at 6:59 PM, Sam Tobin-Hochstadt <notifications@github.com> wrote:
> 
> The BSL program: (define car 5) produces the error message car: this name was defined previously and cannot be re-defined. Of course, the previous definition is part of the language, not in the student program. If the error message mentioned that things could be built-in to the language, that would be helpful.
> 
> I suggest: "this name is already defined in this file or is part of the language and cannot be re-defined". I'm happy to make the change if that sounds good to people.
> 
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 


Guillaume wrote a guide for articulating error messages. Please consult, it’s in our documentation. (It says which words to use, which to avoid.) I’d be happy to look over your suggestion.

**Comment by samth** [comment]
How about "this name is already defined or is part of the language and cannot be re-defined"? I think that follows the guidelines.

**Comment by rfindler** [comment]
Why not have two different error messages, one for imported variables and one for lexically bound ones?

**Comment by mfelleisen** [comment]
The message is fine but I’d prefer Robby’s solution (if feasible).

**Comment by samth** [comment]
I created a PR that implements @rfindler's suggestion.
