### ISSUE TITLE
Printing in documentation examples inconsistent with DrRacket

### ISSUE THREAD

**Issue by dvanhorn** [racket/htdp#40]
The printer for BSL examples in the docs is not set up to correspond to how DrRacket prints values.  So for example, students see `#(struct:posn 3 3)` instead of `(make-posn 3 3)`.  Also, `#true` is printed as `#t`.

https://docs.racket-lang.org/htdp-langs/beginner.html#%28part._htdp-beginner._.Posns%29

**Comment by mfelleisen** [comment]
afcc42e closes this one. [This took way longer than it should have but thanks for pushing. Sometimes I question Racket. Should I go back to Pascal :-) ]
