### ISSUE TITLE
`check-expect` does not work as the only form in a `lang/htdp-beginner` module`

### ISSUE THREAD

**Issue by samth** [racket/htdp#41]
This program:

```
(module m lang/htdp-beginner (check-expect 1 1))
```

produces the error `check-expect: found a test that is not at the top level`.

This isn't a problem directly in Beginning Student et al, but it does manifest with the handin server, meaning that submitting files with just one `check-expect` in them fails with an error that students can't understand.

cc @pnwamk

**Comment by mfelleisen** [comment]
Have you had students who did this?

**Comment by pnwamk** [comment]
This was discovered while trying to make a minimal example of a separate issue. I'm not aware of any students who ran into this.

**Comment by mfelleisen** [comment]
Thanks. (I am putting 1100 commas back into 2e.)
