### ISSUE TITLE
batch-io limitations

### ISSUE THREAD

**Issue by Victorious3** [racket/htdp#49]
`read_file` mentions `file-exists?` but it's not provided. Is there any specific reason for this?

Furthermore, the file operations are very limited currently. Apart from the lack of `file-exists?` there's also no way to
- delete files
- create folders
- list folder contents

Being a student myself, I wanted to use batch-io for creating save files for an application using the universe teachpack.

**Comment by mfelleisen** [comment]
The lack of `file-xists?` is an oversight. 

The other operations are beyond the scope of HtDP, which is what this teachpack serves.

**Comment by Victorious3** [comment]
Oh well, maybe for a feature release? Especially since these operations are relatively simple and don't require any advanced language constructs. I don't know if this is the right place to make suggestions though.

Here is a first draft:

```racket
; Returns true if the specified file is a folder
(folder? f) -> boolean?
  f : (and/c string? file-exists?)

; Creates a folder, analog to write-file
(make-folder f) -> string?
  f : string?

; Lists all contents of a folder
(folder-list-files f) -> (listof string?)
  f : (and/c string? folder? file-exists?)

; Returns the parent folder of a file
(parent-folder? f) -> string?
  f : (and/c string? file-exists?)

; Deletes a file. Returns the parent folder on success, otherwise signals an error
(delete-file f) -> string?
  f : string?
```
Under the assumption that a folder is a special kind of file. The other functions could be updated to signal appropriate errors if they were called with a folder.

Additionally, I would change `write-file` to accept an additional (optional?) parameter:
```
(write-file f cntnt mode) -> string?
  f : (or/c 'standard-out 'stdout string?)
  [mode: (or/c 'append 'overwrite)]
```
Where `'append` would insert at the end of a file and `'overwrite` would be equivalent to the current behavior.

**Comment by mfelleisen** [comment]
[[ I understand how to add the existing functions but, as I said, this doesn't fit the curriculum. I'd rather see you switch to Racket and use the universe library from there. Then you get the best of both worlds. ]]

**Comment by Victorious3** [comment]
Aight. I was mainly concerned about the absence of `file-exists?`. Thanks for the clarification.
