### ISSUE TITLE
Handin rejecting code which modifies a DrRacket-modified image

### ISSUE THREAD

**Issue by rrose1** [racket/htdp#51]
Steps to reproduce:
1. Run `(require 2htdp/image)`
2. Paste an image (drracket.png, for example) from clipboard into the Interactions window
3. Apply `scale 1` to this image and hit enter.
4. Copy and paste the result to the Definitions window.
5. Apply `scale 1` to the result in the Definitions window. The Definitions window should now contain `(require 2htdp/image)`
 `(scale 1 ...)`
where ... is replaced with the DrRacket-modified image.
6. Submit the file to a Handin server configured with a checker script which evaluates the submission.

The code runs as expected in DrRacket, but submission to a Handin server will give an error:

> submit error: Error in your code --
> scale: expects an image as second argument, given '(instantiate (class ...) ...)

**Comment by samth** [comment]
Fixed in racket/handin#23
