### ISSUE TITLE
signatures interfere with structures in ISL

### ISSUE THREAD

**Issue by mfelleisen** [racket/htdp#52]
See https://github.com/racket/racket/issues/1976 for details. 

@ccshan 
@schackbrian2012

edit: added URL to racket issue ref

**Comment by mikesperber** [comment]
I just pushed a patch to deinprogramm-signature that has a custom error message for this situation:

function call: expected a function after the parenthesis, but received a signature

I'm sure it's not optimal, so happy to hear suggestions for improvement.

**Comment by mfelleisen** [comment]
Thanks! This should work fine. 

I would probably have used the error message rewriter to fix up the message.

**Comment by schackbrian2012** [comment]
Thank you for changing the error message!

**Comment by mikesperber** [comment]
Closing this one as it's been addressed.
