### ISSUE TITLE
Error highlight sometimes disappears after a period of time

### ISSUE THREAD

**Issue by gfbee** [racket/htdp#67]
It's a bit non-deterministic, but I can get it fairly reliably on Mac OS with: ISL previous chosen, launch DrRacket
```
Welcome to DrRacket, version 7.0 [3m].
Language: Intermediate Student; memory limit: 2000 MB.
```
click in the Definitions and type `(=)`, then either click Run or type Command-R and wait while doing nothing for twenty seconds.

**Comment by shhyou** [comment]
Closing. Might have been fixed at some point between 7.0bc and 8.15cs.
