### ISSUE TITLE
ISL HOF docs use lambda expressions in examples

### ISSUE THREAD

**Issue by dvanhorn** [racket/htdp#81]
Many of the higher-order functions in the docs for ISL use examples that involve lambda, which is only available (as an expression form) starting in ISL+.  This is sure to confuse students and means copy/pasting examples will result in errors (lambda: found a lambda that is not a function definition).

lambda expressions are used in: andmap, build-list, build-string, compose, filter, foldl, foldr, for-each, map, ormap, and procedure?.

**Comment by mfelleisen** [comment]
closed with  97e63b33

**Comment by sorawee** [comment]
This is still not completely resolved. The example for [`check-within`](https://docs.racket-lang.org/htdp-langs/beginner.html#%28form._%28%28lib._lang%2Fhtdp-beginner..rkt%29._check-within%29%29) uses `lambda` in every *SL.

**Comment by mfelleisen** [comment]
Thanks.
