### ISSUE TITLE
Inconsistent signatures for varaiable arity HOFs in ISL (and above)

### ISSUE THREAD

**Issue by dvanhorn** [racket/htdp#82]
There are some inconsistencies with the signatures given for HOFs with variable arity in ISL (and above).  For example:
```
(andmap p? [l]) → boolean
p? : (X ... -> boolean)
l : (listof X) = ...

(ormap p? l) → boolean
p? : (X -> boolean)
l : (listof X)

(map f l ...) → (listof Z)
f : (X ... -> Z)
l : (listof X)
```
andmap should use the map style notation and ormap should be revised to reflect its variable arity.

**Comment by mfelleisen** [comment]
closed with  97e63b33
