### ISSUE TITLE
check-expect mis-blamed for error outside testing

### ISSUE THREAD

**Issue by ccshan** [racket/htdp#87]
Steps to reproduce: In the Beginning Student Language (or Intermediate Student Language), run the following program:
```
(check-expect (g 30) "goodbye")
(f 40)
(define (f x) "hello")
(define (g y) "goodbye")
```

Expected:
```
f is used here before its definition
The test passed!
```

Actual:
```
f is used here before its definition
Ran 1 test.
0 tests passed.
No signature violations.

Check failures:
	check-expect encountered the following error instead of the expected value, "goodbye". 
   :: g is used here before its definition
in slattery.rkt, line 1, column 0 caused by expression in slattery.rkt, line 1, column 15 
```

Bug found by Austin Slattery.

Environment: DrRacket, version 7.4, english; Installed tools:
- Algol 60
- Signatures
- DeinProgramm
- DeinProgramm
- Browser
- Check Syntax
- Graphical Debugger
- Macro Stepper
- Repository Time Stamp
- Version
- FrTime Language
- How to Design Programs
- The Stepper
- Test Engine
- Text Box
- Lazy Racket
- Optimization Coach
- Quickscript
- RackUnit DrRacket integration
- Slideshow
- Swindle

macOS High Sierra, Version 10.13.6, MacBook Pro (Retina, 13-inch, Early 2015)

**Comment by mfelleisen** [comment]
I added the test via 8e1734c0 

But it isn't fixed. Interestingly #lang htdp/bsl is a bit better on this one.

**Comment by ccshan** [comment]
Is this issue closed because it won't be fixed?

**Comment by mfelleisen** [comment]
No it is closed because there is a failing test case in the repo now.

**Comment by samth** [comment]
Note that the actual commit is 1ad5ee3722f9f2.

**Comment by ccshan** [comment]
Ok, I'm not familiar with the meaning of putting a file inside `htdp-test/tests/test-engine`, but I want to reiterate that the correct behavior includes an error (but not a test failure).

**Comment by mfelleisen** [comment]
> On Nov 13, 2019, at 9:45 PM, Chung-chieh Shan <notifications@github.com> wrote:
> 
> Ok, I'm not familiar with the meaning of putting a file inside htdp-test/tests/test-engine, but I want to reiterate that the correct behavior includes an error (but not a test failure).
> 
> 

Correct. #lang htdp/bsl does this correctly and the teaching language test-engine does not. (It will take me a while to figure out how this is reported as a failing test case.)

**Comment by samth** [comment]
I think the bug is that execution of the module stops because of the exception, and thus fails to define `g` at all, leading to this problem. Here's a simpler program with the same behavior:

```
(check-expect (f 1) 1)
(+ "foo")
(define (f x) x)
```

Also, `#lang htdp/bsl` avoids this problem entirely because it doesn't do the weird things that the test-engine tool does, and so simply stops execution when the first error happens.
